---
account_id: "579878096224"
region: 'eu-west-2'

component: 'test'

work_directory: 'build'
configuration_directory: "%{hiera('work_directory')}/%{hiera('source_directory')}"

private_zone_id: 'Z2CDAFD23Q10HO'
vpc_cidr: "10.1.0.0/16"
availability_zones:
  - "eu-west-2a"
  - "eu-west-2b"

lambda_ingress_cidr_blocks:
  - "10.0.0.0/8"
lambda_egress_cidr_blocks:
  - "0.0.0.0/0"

lambda_function_name: "test-lambda-resource-%{hiera('deployment_identifier')}"
lambda_description: "test terraform-aws-lambda"

lambda_zip_path: 'lambda.zip'
lambda_handler: "handler.hello"

lambda_environment_variables: '{"TEST_ENV_VARIABLE"="test-value"}'

deploy_in_vpc: "yes"
lambda_reserved_concurrent_executions: -1

tags:
  key: "value"
