---
source_directory: "spec/infra/harness"
state_file: "%{hiera('project_directory')}/state/harness.tfstate"
vars:
  region: "%{hiera('region')}"

  component: "%{hiera('component')}"
  deployment_identifier: "%{hiera('deployment_identifier')}"
  deployment_label: "%{hiera('deployment_label')}"
  deployment_type: "%{hiera('deployment_type')}"
  deploy_in_vpc: "%{hiera('deploy_in_vpc')}"

  account_id: "%{hiera('account_id')}"
  tags: "%{hiera('tags')}"


  lambda_zip_path: "%{hiera('lambda_zip_path')}"
  lambda_ingress_cidr_blocks: "%{hiera('lambda_ingress_cidr_blocks')}"
  lambda_egress_cidr_blocks: "%{hiera('lambda_egress_cidr_blocks')}"
  lambda_environment_variables: "%{hiera('lambda_environment_variables')}"
  lambda_function_name: "%{hiera('lambda_function_name')}"
  lambda_description: "%{hiera('lambda_description')}"
  lambda_handler: "%{hiera('lambda_handler')}"
